### ISSUE TITLE
Characters not echoing after after using autocomplete

### ISSUE THREAD

**Issue by j0hax** [gennaro-tedesco/element#1] opened 2021-07-06 19:44 UTC
Hello, I am the maintainer for the element package on [NixOS](https://nixos.org/)!

I noticed that after using autocomplete, characters do not echo on the command line after the program exits. The only way known to me to fix this is by executing `reset`. This happens when using regular `bash` and `bash --posix`.

I've included an asciinema demonstrating the problem. Unfortunately I'm not familiar with Go, so I can't provide a PR, but I'd love to see a fix for this program!

[![asciicast](https://asciinema.org/a/cDOHFmuwwSIeMwjsHEsulTjmk.svg)](https://asciinema.org/a/cDOHFmuwwSIeMwjsHEsulTjmk)

**Comment by gennaro-tedesco** [comment] 2021-07-07 08:42
Good morning and thank you for looking into `element`! 

I confirm that with `bash` I am seeing the same problem (which does not manifest if using `zsh` or `fish`); in particular it seems that such problem occurs only when exiting after the prompt selection: if instead the program exits because of a wrong command or an incorrect query, such inconsistency does not reproduce.

I would be inclined to think that the responsibility lies in the library I am using to show the prompt, namely [go-prompt](https://github.com/c-bata/go-prompt) and the way it passes the exit codes to the shell (I have re-created a minimal prompt example independent of `element` where I see the same). If this is the case (I am not entirely sure yet, will do more testing) I believe we would have to open an issue in that project instead.

Just for reproducibility sake: could you report the specific of the system you are using (terminal, shell, operating system)?

**Comment by gennaro-tedesco** [comment] 2021-07-07 09:35
I have reproduced the issue by copying and pasting the [documentation example](https://github.com/c-bata/go-prompt#go-prompt): see below

https://user-images.githubusercontent.com/15387611/124736401-42a0ac00-df17-11eb-81e2-a0bca43da430.mov

so the problem is indeed the way `go-prompt` interacts with bash (independent of the rest of the code in `element`). Only after issuing `reset` does the prompt echo the characters again.

Please validate that this is the case on your hand too and if so we can open an issue there and reference this one for completeness.

**Comment by j0hax** [comment] 2021-07-07 14:03
>Just for reproducibility sake: could you report the specific of the system you are using (terminal, shell, operating system)?

- Terminal: Konsole
- Shell: bash 4.4.23
- OS: NixOS 21.11.20210704.20887e4

I could also reproduce the bug by running the dependency's provided [examples](https://github.com/c-bata/go-prompt/tree/master/_example).

I looked into the project and it appears this issue has already been reported in https://github.com/c-bata/go-prompt/issues/228, https://github.com/c-bata/go-prompt/issues/233 and a fix is provided by https://github.com/c-bata/go-prompt/pull/239. It may be nice to integrate as a [patch](https://patch-diff.githubusercontent.com/raw/c-bata/go-prompt/pull/239.patch).

**Comment by gennaro-tedesco** [comment] 2021-07-07 15:27
So it seems that [the PR](https://github.com/c-bata/go-prompt/pull/239) is waiting to be merged. I would say we wait for the merge so that I can re-release `element` with the new dependency.

**Comment by DUOLabs333** [comment] 2021-09-11 00:45
Yes -- for those that want an immediate fix: if you do `git clone --depth=1 https://github.com/Xiami2012/go-prompt -b fix-termios-bad-save`, cd into `go-prompt`, then `go build`, then do `go get -u -v github.com/gennaro-tedesco/element` again, it should work.

**Comment by gennaro-tedesco** [comment] 2021-11-16 10:51
The PR has been merged, I am closing this as the issue should be fixed.

**Closed as completed by gennaro-tedesco** 2021-11-16 10:51 UTC
